# Add application configuration variables here, as shown below.
# Set as Heroku environment variables using 'rake figaro:heroku'

SITE_NAME: 'Rails 4 SaaS Starter Kit'

TWITTER_URL: 'https://twitter.com/<twiiter handle>'
FACEBOOK_URL: 'https://www.facebook.com/<facebook handle>'
GPLUS_URL: 'https://plus.google.com/+<google plus handle>'

########################## -IMPORTANT- ##########################
# THE FOLLOWING ARE VARIABLES THAT YOU WILL ALSO SEE BELOW IN THE 
# PRODUCTION SECTION. PLEASE FILL THE IMMEDIATE VARIABLES WITH 
# DEVELOPMENT & TEST CONFIGS AND THEN PROCEED TO PRODUCTION

HOST_URL: 'localhost:3000'
STRIPE_API_KEY: '<stripe test secret key>'
STRIPE_PUBLIC_KEY: '<stripe test publishable key>'

production:  
  HOST_URL: '<site url>'
  STRIPE_API_KEY: '<stripe live secret key>'
  STRIPE_PUBLIC_KEY: '<stripe live publishable key>'
